# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-10-16 11:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artical', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articalmodel',
            old_name='categroy',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='articalmodel',
            old_name='des',
            new_name='desc',
        ),
    ]
