# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-10-17 02:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artical', '0003_auto_20171017_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='articalmodel',
            name='read_count',
            field=models.IntegerField(default=0),
        ),
    ]
