# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-10-26 12:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artical', '0006_commonmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CommonModel',
            new_name='CommentModel',
        ),
    ]
